# MySQL DB Connectivity
spring:
  application:
    name: "grocery-booking-api"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    username: 'root' #${MYSQL_USER}
    password: 'root' #${MYSQL_PASSWORD}
    url: "jdbc:mysql://localhost:3306/hdplus_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC&allowPublicKeyRetrieval=true" #${MYSQL_URL}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: info
    org:
      springframework:
        security : DEBUG