name: ZAP Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '36 0 * * 4'

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start your Spring Boot app
        run: |
          ./mvnw spring-boot:run &
          sleep 30  # give the app some time to start

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8080 -r report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: report.html
